spring:
  profiles.active: development
---
spring:
  application:
    name: "ALFA TEST"
  profiles: development

server:
  port: 8080

service:
  integration-test:
    wiremock-host: localhost
    wiremock-port: 8080

feign:
  name: client
  hystrix:
    enabled: false
  okhttp:
    enabled: true

app:
  rate:
    api-url: https://openexchangerates.org
    app-id: 36ea29b7bc80419dafe4ba9632075e95
    general-base: USD
  gif:
    api-url: http://api.giphy.com
    api-key: tPCR00QmV8xyiOig7C9rbfFXvwOVg8jW
    positive-tag: rich
    negative-tag: broke

static:
  offsets:
    - name: giphy default offset
      value: 1000
    - name: giphy max offset
      value: 4990
---
spring:
  application:
    name: "ALFA TEST"
  profiles: production

server:
  port: 8080
  servlet:
    context-path: /api

service:
  integration-test:
    wiremock-host: localhost
    wiremock-port: 8080

feign:
  name: <must-be-overridden>
  hystrix:
    enabled: false
  okhttp:
    enabled: true

app:
  rate:
    api-url: <must-be-overridden>
    app-id: <must-be-overridden>
    general-base: USD
  gif:
    api-url: <must-be-overridden>
    api-key: <must-be-overridden>
    positive-tag: <must-be-overridden>
    negative-tag: <must-be-overridden>

static:
  offsets:
    - name: giphy default offset
      value: 1000
    - name: giphy max offset
      value: 4990
---
spring:
  application:
    name: "ALFA TEST"
  profiles: test

server:
  port: 8080
  servlet:
    context-path: /api

service:
  integration-test:
    wiremock-host: localhost
    wiremock-port: 8080

feign:
  name: client
  hystrix:
    enabled: false
  okhttp:
    enabled: true

app:
  rate:
    api-url: https://openexchangerates.org
    app-id: 5db496f900bd4fbe9a537911844e0b44
    general-base: USD
  gif:
    api-url: http://api.giphy.com
    api-key: tPCR00QmV8xyiOig7C9rbfFXvwOVg8jW
    positive-tag: rich
    negative-tag: broke

static:
  offsets:
    - name: giphy default offset
      value: 1000
    - name: giphy max offset
      value: 4990